//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwoDesign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.Orders = new HashSet<Order>();
            this.Shippers = new HashSet<Shipper>();
        }
    
        public int AddressID { get; set; }
        public string AddressName { get; set; }
        public string Text { get; set; }
        public string City { get; set; }
        public string Region { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Shipper> Shippers { get; set; }
    }
}
