//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwoDesign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brand
    {
        public Brand()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int BrandID { get; set; }
        public string BrandName { get; set; }
        public string Description { get; set; }
        public Nullable<int> ImageID { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual Image Image { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}
