//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwoDesign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public Image()
        {
            this.Brands = new HashSet<Brand>();
            this.Categories = new HashSet<Category>();
        }
    
        public int ImageID { get; set; }
        public string ImagePath { get; set; }
        public string Description { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual ICollection<Brand> Brands { get; set; }
        public virtual ICollection<Category> Categories { get; set; }
    }
}
