//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwoDesign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int OrderID { get; set; }
        public int CustomerID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> ShippedDate { get; set; }
        public Nullable<int> ShipperID { get; set; }
        public Nullable<decimal> Freight { get; set; }
        public string ShipName { get; set; }
        public Nullable<int> ShipAddressID { get; set; }
        public Nullable<int> OrderStatusID { get; set; }
        public Nullable<bool> InBascet { get; set; }
        public string CargoTrackingNo { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual OrderStatu OrderStatu { get; set; }
        public virtual User User { get; set; }
    }
}
