//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwoDesign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Orders = new HashSet<Order>();
            this.UserAddresses = new HashSet<UserAddress>();
        }
    
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public int RoleID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string PhoneNumber { get; set; }
        public string PasswordQuestion { get; set; }
        public string PaswordAnswer { get; set; }
        public Nullable<bool> IsAprowed { get; set; }
        public Nullable<bool> IsLockedOut { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<UserAddress> UserAddresses { get; set; }
    }
}
