//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwoDesign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAddress
    {
        public int UAddressID { get; set; }
        public int UserID { get; set; }
        public string Name { get; set; }
        public string Text { get; set; }
        public string City { get; set; }
        public string Region { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual User User { get; set; }
    }
}
